### ISSUE TITLE
Changing block order causes Domoticz to crash

### ISSUE THREAD

**Issue by bizziebis** [robgeerts/Dashticz#21]
When I try to change the block order Domoticz immediately chrashes.
This is the URL which was used:

(h)ttp://10.0.0.80/json.htm?type=command&param=updateuservariable&idx=46&vname=dashticz_blockorder&vtype=2&vvalue=device19,device5,device18,device6,device647,device646,device648,device224,device223,device644,device249,device82,device380,device387,device60,device504,device207,device503,device277,device661&jsoncallback=jQuery213012688801996409893_1424722069723&_=1424722069754

Strange thing is that it only happens with one of my floorplans. With the other plans I can move blocks.

**Comment by bizziebis** [comment]
Ok, When I change the string by hand in Domoticz I get a reply that the string is too big. Maybe that's the issue

**Comment by robgeerts** [comment]
Yeah, I noticed that before, unfortunately... 
That's why I initially decided to make use of PHP, but the downside is that users will have to install it on a webserver with PHP-support in their network. That's why it's not required at the moment. Although, for many users this won't be a problem but for some it is. I can change this problem with a fix (not saving blocks as 'device43' but d43), but some users with a lot of blocks will stil have problems...

**Comment by robgeerts** [comment]
Fix is now available in latest version!
